#!/usr/bin/env perl
package password;

use strictures;

use Getopt::Long  ();
use Pod::Usage    ();
use Crypt::Random ();

our $VERSION = '2.0.1';

__PACKAGE__->_run( [ @ARGV ] ) unless caller;

sub new {
    my $class      = shift;
    my $attributes = {
        length => undef,
        @_,
    };

    die "length must be a positive integer\n"
        if $attributes->{length} !~ /^\d+$/ || $attributes->{length} < 1;

    my $self = $attributes;

    bless $self, $class;

    return $self;
}

sub generate {
    my $self = shift;

    my @characters = ( 'A' .. 'Z', 'a' .. 'z', 0 .. 9 );
    my $password   = join '', map {
        $characters[
            Crypt::Random::makerandom_itv(
                Lower => 0,
                Upper => scalar @characters
            )
        ]
    } 1 .. $self->{length};

    return $password;
}

sub _run {
    my $class = shift;
    my $args  = shift;

    # define the defaults
    my $opt = { length => 12 };

    Getopt::Long::GetOptionsFromArray(
        $args,
        'length=i' => \$opt->{length},
        'version'  => \$opt->{version},
        'help'     => \$opt->{help},
        'man'      => \$opt->{man},
    ) or Pod::Usage::pod2usage( -exitval => 1, -verbose => 0 );

    Pod::Usage::pod2usage( -exitval => 0, -verbose => 1 ) if $opt->{help};
    Pod::Usage::pod2usage( -exitval => 0, -verbose => 2, noperldoc => 1 ) if $opt->{man};

    if ( $opt->{version} ) {
        print "$VERSION\n";
        exit;
    }

    my $object = $class->new( length => $opt->{length} );

    print $object->generate() . "\n";

    return;
}

1;

__END__

=pod

=head1 NAME

password - generate cryptographically secure passwords

=head1 SYNOPSIS

  password [--length] <int>
           [--version]
           [--help] [--man]

=head1 OPTIONS

  --length     how long you want the password (defaults to 12)
  --version    print the version and exit
  --help       print this dialogue
  --man        display the full documentation

=head1 DESCRIPTION

password generates cryptographically secure random passwords, using alphanumeric characters with case variation.

The logic can be used directly as a script or used as a module.

=head1 EXAMPLES

=head2 As a script

=over

=item Get a 12 character length password

  password

=item Get a 32 character length password

  password --length 32

=back

=head2 As a module

=over

=item Get a 12 character length password

  require 'password';
  my $object = password->new( length => 12 );

  print $object->generate() . "\n";  

=back

=head1 SUBROUTINES/METHODS

=head2 new

Constructor for the password object.

=head3 ARGUMENTS

=over

=item length

The length of the password to be generated.

Must be a positive integer.

=back

=head3 RETURNS

The password object.

=head3 EXCEPTIONS

=over

=item length must be a positive integer

This exception is thrown when verification of the length argument doesn't pass.

=back

=head2 generate

Generates the password based on the length as defined through the constructor. 

=head3 ARGUMENTS

None.

=head3 RETURNS

The generated password string.

=head1 EXIT STATUS

=over

=item 0 - Indicates completion without failure

=item 1 - Indicates failure

=back

=head1 DEPENDENCIES

=over

=item strictures

=item Getopt::Long

=item Pod::Usage

=item Math::Pari

=item Crypt::Random

=back

=head1 AUTHOR

Blaine Motsinger, <blaine@renderorange.com>

=head1 LICENSE AND COPYRIGHT

This software is available under the MIT license.

Copyright (c) 2019 Blaine Motsinger

=cut
